language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "pip install -r testing-requirements.txt"
# command to run tests
script:
  - tests/run_tests.sh
  - samples/stateful_autonomous/robot.py coverage test