language: python
sudo: false
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r testing-requirements.txt"
# command to run tests
script:
  - tests/run_tests.sh