language: python
sudo: false
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r testing-requirements.txt"
# command to run tests
script:
  - tests/run_tests.sh
  - samples/magicbot_simple/robot.py coverage test
  - samples/navx_mxp/robot.py coverage test
  #- samples/navx_rotate_to_angle/robot.py coverage test
  - samples/stateful_autonomous/robot.py coverage test